version: '3.8'
services:
  movies:
    image: harshraj95340/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: harshraj95340/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: harshraj95340/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: harshraj95340/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
